### ISSUE TITLE
Support subscription GraphQL

### ISSUE THREAD

**Issue by sahb1239** [sahb1239/SAHB.GraphQLClient#34]

**Comment by saba-sabrin** [comment]
@sahb1239 Is the subscription support added to this client library? Could you please provide any examples? Thanks.

**Comment by sahb1239** [comment]
Hello @saba-sabrin,
It's unfortunately not supported at the moment. I will in the next week develop support for generating the subscription query. You can then use another library for managing the subscription and deserialization. I will update this issue with a example when the support for generating the subscription query is developed

I'm currently working on full support of subscriptions, unions, interfaces and refactoring of existing code. I will update you in this issue when this is done.

**Comment by sahb1239** [comment]
A preview packages has now been published here:
https://www.nuget.org/packages/SAHB.GraphQL.Client.Subscription/

A example on how to use can be found here:
https://github.com/sahb1239/SAHB.GraphQLClient/blob/release/2.0.0-beta1/examples/SAHB.GraphQL.Client.Subscription.Examples/Program.cs
