### ISSUE TITLE
Allow complex arguments for GraphQL Queries

### ISSUE THREAD

**Issue by mrtes** [sahb1239/SAHB.GraphQLClient#42]
Hi,

currently, the `GraphQLQueryArgument` class only supports query arguments with simple types.
I would like to be able to include "complex" types in my queries, like this:
```
IGraphQLHttpClient client = GraphQLHttpClient.Default();

var response = await client.Query<Query>("https://mpjk0plp9.lp.gql.zone/graphql", 
    arguments: new GraphQLQueryArgument("test", new {Id = 1, Identifier = "test"}));
```

Currently, I have to serialiye an object like this beforehand to fit the signature of the ``GraphQLQueryArgument` constructor: 
```
IGraphQLHttpClient client = GraphQLHttpClient.Default();

var response = await client.Query<Query>("https://mpjk0plp9.lp.gql.zone/graphql", 
    arguments: new GraphQLQueryArgument("test", JsonConvert.SerializeObject(new {Id = 1, Identifier = "test"})));
```

However, this leads to issues with the generated Json, resulting in:

```
"variables": {
        "test": "{\"Id\":1, \"Identifier\":\"test\"}"
    }
}
```

which will not be deserialized correctly.

Suggested fix: Change the type of `GraphQLQueryArgument.ArgumentValue` to object.

**Comment by sahb1239** [comment]
Hi Martin,

This looks like a good idea. Would it be possible for you to submit a PR?  

I will then publish in one of the following days in a new release.

**Comment by sahb1239** [comment]
I have created a PR for it, if you have any additional testcases or possible changes you are welcome to submit them.
