### ISSUE TITLE
Option to add default header

### ISSUE THREAD

**Issue by sarul84** [sahb1239/SAHB.GraphQLClient#63]
Hi,
It would be great if there is an option to add request header to executor class. We were not able to access httpclient object at run since it is declared as private variable.

**Comment by sahb1239** [comment]
Hi,

Currently the only way for adding default request headers is to implement the `IGraphQLHttpExecutor`.

The default implementation of `IGraphQLHttpExecutor` can be found here:
https://github.com/sahb1239/SAHB.GraphQLClient/blob/develop/src/SAHB.GraphQLClient/Executor/GraphQLHttpExecutor.cs

I plan to make it possible to add default headers and modifying the HttpRequestMessage per request in version 2.0 of the client.

**Comment by sahb1239** [comment]
It's now possible to add default request headers to the executor class (in version 2.0.0)
`
var client = GraphQLHttpClient.Default();
client.HttpExecutor.Client.DefaultRequestHeaders.Add("header", "value");
`
