### ISSUE TITLE
Websocket connection fields should be lower case

### ISSUE THREAD

**Issue by chelliwell** [sahb1239/SAHB.GraphQLClient#67]
Hi, have just starting exploring this client today, and found an issue with subscriptions: I am using an Apollo server, and it objects (i.e. the connection fails) to 'id'/'type'/'payload' being capitalized in the websocket messages.
If you restore the 'DataContract' stuff in OperationMessages.cs (as per the original from graphql-dotnet/server), then it connects to Apollo successfully.

**Comment by sahb1239** [comment]
Hi, I will look into that tomorrow - thanks for your report.

**Comment by sahb1239** [comment]
This issue should now be fixed - I will publish a new version to NuGet with the fix.
This should be available [here](https://www.nuget.org/packages/SAHB.GraphQL.Client.Subscription/2.0.1)
