### ISSUE TITLE
Introspection

### ISSUE THREAD

**Issue by chelliwell** [sahb1239/SAHB.GraphQLClient#71]
I realise this is only on the develop branch, but what goals do you have in mind for this?
I have a closed server/client system, but nonetheless it would improve code maintainability if the client could, for example, discover the fields provided by the server's subscriptions and create a 'subscribe' query containing everything - i.e. construct it's own 'wildcard' on the fly. It gets tricky when an object format/name gets changed in the server but you forget to update the client! (A smart client could also perform some confirmation that the server schema matches the query it's planning on doing, and flag up a more informative error if not).
So I wondered how far you'd got with this, and whether you could give me any 'getting started' tips so I could go exploring along the lines of the above scenario?
Thanks.

**Comment by chelliwell** [comment]
Ah ok, yep I see. #1 and #2 would be my most 'like to haves'. 
I agree about not validating before each query, although if the schema was fetched once at start-up and the validator could run against the in-memory copy? Certainly adequate to perform the validation as part of testing though - I control the client apps so I know what queries they will be attempting.
I'll explore it on the develop branch. Thanks

**Comment by sahb1239** [comment]
I have created issue #94 to be more specific on remaining work (bullet 4). If you think this issue is not resolve you are welcome to open it again.
