### ISSUE TITLE
Enum in subscription 'query'

### ISSUE THREAD

**Issue by chelliwell** [sahb1239/SAHB.GraphQLClient#77]
I can add a string argument to a subscription:
```
        public class MessageSubscription
        {
        [GraphQLArguments("src", "String", "fromSrc", IsRequired = true)]
        public Message subRd { get; set; }
        }

        public class Message
        {
            public string src { get; set; }
            public Record record { get; set; }
        }


        var operation = await graphQLSubscriptionClient.ExecuteOperation<MessageSubscription>(new GraphQLQueryArgument("fromSrc", "SB"));
```
Gives a query:
```
"{\"query\":\"subscription subRd{subRd(src:\\\"SB\\\"){src record}}\"}"
```
Trouble is, the argument actually needs to be an enum:
```
        public enum RdSrc
        {
            SB,
            XB
        }
```
for query
```
"{\"query\":\"subscription subRd{subRd(src:SB){src record}}\"}"```
```
Is this possible..?

**Comment by sahb1239** [comment]
When executing the operation you should use the enum in the GraphQLQueryArgument. For example:

var operation = await graphQLSubscriptionClient.ExecuteOperation<MessageSubscription>(new GraphQLQueryArgument("fromSrc", RdSrc.SB));

This should generate the correct query.

**Comment by sahb1239** [comment]
You should put the name of the enumtype in GraphQL. You can find this name using introspection for example using GraphQL Playground or GraphiQL. It could for example be RdSrc.

**Comment by chelliwell** [comment]
Ok (can't believe I hadn't tried that!). Because of the IsRequired, it seems I need "RdSrc!".

I'm still finding it difficult to tie up both ends though. The above sends 0 as the arg value, which my server rejects since it isn't SB or XB. I can get the textual form of the enum, but that is then a string and so (obviously) gets quoted by GraphQLQueryArgument....
Although the [Apollo] server docs suggest the enums can have alternative values, I've not got it to accept 0 or "XB" - and in any case that would kinda ignore the use of nicely typed enums?

**Comment by chelliwell** [comment]
This may or may not be a similar thing, but I'm also having trouble doing an introspection ValidateGraphQLType on a query which also takes this enum as an argument:
"Argument at QryRdByEmitter has a invalid type. Expected is , actual is RdSrc!."

**Comment by sahb1239** [comment]
Hello,

You can use EnumMember (Newtonsoft.Json).

```
public enum RdSrc
{
   [EnumMember(Value = "SB")]
   SB,
   [EnumMember(Value = "XB")]
   XB
}
```

Would you create a issue on the other issue with the introspection? This is clearly a but

**Comment by chelliwell** [comment]
Still trying to work through that suggestion, but isn't it going to still have the problem of giving something of type string, and end up quoted? i.e. 
```
  subscription subRd{subRd(src:"SB"){src record}}
```
whereas an enum param needs to be
```
  subscription subRd{subRd(src:SB){src record}}
```
I suspect some additional classes/types would be needed to support this?

**Comment by sahb1239** [comment]
I have found out the problem is the default way Newtonsoft.Json serializes enums. I have created some [testcode](https://github.com/sahb1239/SAHB.GraphQLClient/commit/059107a9e003eac431e3254f794ab155f6051e54) which shows how it's possible to override the default behaviour.

**Comment by chelliwell** [comment]
I'm not surprised that its an awkward case - in any programming language an enum is just used as-is, as in GraphQL. But through any intermediate serializing like JSON/XML/etc, they tend to quote the 'values'

**Comment by sahb1239** [comment]
You are completely correct. According to the [spec](https://graphql.github.io/graphql-spec/June2018/#sec-Enum-Value) it should be "values are represented as unquoted names". 

This should therefore be handled in this library possible by providing a default custom JsonConverter.

**Comment by sahb1239** [comment]
I have found the problem in `GraphQLQueryGeneratorFromFields`. Currently it uses JsonConvert to serilize the value at line 246. This should be handled in a better way.

**Comment by sahb1239** [comment]
It should now be fixed for all inlined arguments. I'm not sure if it should also be updated for variables would you check if your server has the same problem for not inlined arguments?

`[GraphQLArguments("src", "RdSrc!", "fromSrc", inlineArgument: false, isRequired: true)]`

**Comment by chelliwell** [comment]
I've tried both query and subscription, with inline both true and false - all four cases are being generated correctly, and accepted by my server.
