### ISSUE TITLE
Methods for constructing *and validating queries

### ISSUE THREAD

**Issue by chelliwell** [sahb1239/SAHB.GraphQLClient#78]
I'll try to compose this concisely....
I see from the example app that there's a number of ways of constructing queries.
My client app will be wanting to invoke a number of types of Query provided by the server. Sometimes - in GraphQL style - it won't want _all_ the possible fields from a given Query.
Using the class-based method, would that mean defining a query and 'response' class for each permutation of desired fields (and use GraphQLFieldIgnore in them as required)? That would be clean and clear, but a bit of a headache I end up with a lot of permutations.
Using the example's SwapiQuery to illustrate: if I wanted to query Title+Director for all films, or just Title, would that require 'doubling up' on SwapiQuery, FilmConnection _and_ Film?

Are there better ways to build these queries, **but** which would still allow me to validate the query against the introspection schema?

**Comment by sahb1239** [comment]
Currently no. You can however use Skip and Include directives when #74 is implemented. Alternative you can try to define your queries with typeparameters.

It's however on my plan to support "selecting" the output needed for a query using a NewExpression. I currently don't know when I would support this.

**Comment by chelliwell** [comment]
Would you be able to add some documentation on this? I've been looking at the tests added in the commit, to get some clues, but obviously that's not always easy.
Even if it's without actual code examples to start with - if you could summarise just what is possible then I can go examining test cases to understand it.
That's a bit of a general comment, in fact: I know docs can be time-consuming but, as I say, even knowing what kinds of things are possible is a start.
